name: 'Amazon ECS "Start Task" Action for GitHub Actions'
description: 'Starts an Amazon ECS task'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The arn to the ECS task definition'
    required: true
  subnet:
    description: 'The subnet of the ECS task VPC'
    required: true
  security-group:
    description: 'The security group of the ECS task VPC'
    required: false
  service:
    description: 'The name of the ECS service in which to start the task in.'
    required: false
  cluster:
    description: "The name of the ECS service's cluster in which to start the task in.  Will default to the 'default' cluster"
    required: false
  container-commands:
    description: "JSON mapping from container names to container commands"
    required: false
  wait-for-task:
    description: "Whether to wait for the task to finish"
    required: false
outputs:
  task-arn:
    description: 'The ARN of the started task'
runs:
  using: 'node12'
  main: 'dist/index.js'
